// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'

    show defaultTargetPlatform, kIsWeb, TargetPlatform;


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnpWk3IrZ6wJMD8u8TUYouwiKmjri2kqc',
    appId: '1:16153775177:web:a89d00b7bb0b27cb114398',
    messagingSenderId: '16153775177',
    projectId: 'griot-f70c0',
    authDomain: 'griot-f70c0.firebaseapp.com',
    storageBucket: 'griot-f70c0.firebasestorage.app',
    measurementId: 'G-5RY0PTL7QQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkt-pR62FPelBcjZv3EfNL-0jpDNwNJA8',
    appId: '1:16153775177:android:4da6ae901323d479114398',
    messagingSenderId: '16153775177',
    projectId: 'griot-f70c0',
    storageBucket: 'griot-f70c0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7xo0XsDLpBALh8lIElAVp3ZVxCCEJbs4',
    appId: '1:16153775177:ios:51a93ca75a9a8338114398',
    messagingSenderId: '16153775177',
    projectId: 'griot-f70c0',
    storageBucket: 'griot-f70c0.firebasestorage.app',
    iosClientId: '16153775177-s19s9ir6te8l0ajfrvt6tmr56v5h975v.apps.googleusercontent.com',
    iosBundleId: 'com.example.griot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7xo0XsDLpBALh8lIElAVp3ZVxCCEJbs4',
    appId: '1:16153775177:ios:51a93ca75a9a8338114398',
    messagingSenderId: '16153775177',
    projectId: 'griot-f70c0',
    storageBucket: 'griot-f70c0.firebasestorage.app',
    iosClientId: '16153775177-s19s9ir6te8l0ajfrvt6tmr56v5h975v.apps.googleusercontent.com',
    iosBundleId: 'com.example.griot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnpWk3IrZ6wJMD8u8TUYouwiKmjri2kqc',
    appId: '1:16153775177:web:4122f8ea51606ef5114398',
    messagingSenderId: '16153775177',
    projectId: 'griot-f70c0',
    authDomain: 'griot-f70c0.firebaseapp.com',
    storageBucket: 'griot-f70c0.firebasestorage.app',
    measurementId: 'G-B1GEK48TLX',
  );
}
